module Image where

imagePaths :: [([Char],[Char])]
imagePaths = [ ("images/grass0.png","0")
             , ("images/grass1.png","1")
             , ("images/grass2.png","2")
             , ("images/grass3.png","3")
             , ("images/grass4.png","4")
             , ("images/grass5.png","5")
             , ("images/grass6.png","6")
             , ("images/grass7.png","7")
             , ("images/grass8.png","8")
             , ("images/grass9.png","9")
             , ("images/playerUp.png","w")
             , ("images/playerUp.png","e")
             , ("images/playerRight.png","d")
             , ("images/playerDown.png","c")
             , ("images/playerDown.png","x")
             , ("images/playerDown.png","z")
             , ("images/playerLeft.png","a")
             , ("images/playerLeft.png","q")
             , ("images/waterUL.png","@")
             , ("images/waterU.png","£")
             , ("images/waterUR.png","$")
             , ("images/waterL.png","%")
             , ("images/water.png","^")
             , ("images/waterR.png","&")
             , ("images/waterDL.png","*")
             , ("images/waterD.png","(")
             , ("images/waterDR.png",")")
             , ("images/fighter0.png","fighter0")
             , ("images/fighter1.png","fighter1")
             , ("images/fighter2.png","fighter2")
             , ("images/fighter3.png","fighter3")
             , ("images/fighter4.png","fighter4")
             , ("images/fighter5.png","fighter5")
             , ("images/fighter6.png","fighter6")
             , ("images/fighter7.png","fighter7") ]
